# -*- coding: utf-8 -*-
"""breast cancer ml

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sInD9gqaHpd7zfCyQShuO8_e4GlrBlpI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/breast-cancer.csv")

df.columns.values

df.head()

df.shape

df.describe()

df.isnull()

df.isnull().sum()

df['diagnosis'].unique()

df['diagnosis']=df['diagnosis'].replace(['M','B'],[1,0])

df

df.diagnosis.unique()

del df['id']

df.isna().sum()

df.skew()

df.columns.values

target=df['diagnosis']
del df['diagnosis']





from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df,target,random_state=0)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_train=pd.DataFrame(scaler.transform(X_train))
X_test=pd.DataFrame(scaler.transform(X_test))

scaler2=MinMaxScaler()
scaler2.fit(X_train)
y_train=pd.DataFrame(scaler2.transform(X_train))
y_test=pd.DataFrame(scaler2.transform(X_test))

X_train

X_test

from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

print(reg.score(X_test,y_test)*100)
print(reg.score(X_train,y_train)*100)

